CREATE TABLE people (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100)
);

CREATE TABLE product (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    quantity INT,
    price DECIMAL(10, 2),
    observation VARCHAR(255),
    people_id BIGINT,
    FOREIGN KEY (people_id) REFERENCES people(id)
);

INSERT INTO people (name, email) VALUES
('Alice Johnson', 'alice.johnson@example.com'),
('Bob Smith', 'bob.smith@example.com'),
('Charlie Brown', 'charlie.brown@example.com'),
('David Wilson', 'david.wilson@example.com'),
('Emma Davis', 'emma.davis@example.com'),
('Fiona Harris', 'fiona.harris@example.com'),
('George Clark', 'george.clark@example.com'),
('Hannah Lewis', 'hannah.lewis@example.com'),
('Ian Walker', 'ian.walker@example.com'),
('Jane Hall', 'jane.hall@example.com'),
('Kyle Young', 'kyle.young@example.com'),
('Laura King', 'laura.king@example.com'),
('Mike Wright', 'mike.wright@example.com'),
('Nina Scott', 'nina.scott@example.com'),
('Oscar Adams', 'oscar.adams@example.com'),
('Paula Baker', 'paula.baker@example.com'),
('Quinn Martinez', 'quinn.martinez@example.com'),
('Rachel Perez', 'rachel.perez@example.com'),
('Sam Turner', 'sam.turner@example.com'),
('Tina Phillips', 'tina.phillips@example.com'),
('Uma Rivera', 'uma.rivera@example.com'),
('Victor Campbell', 'victor.campbell@example.com'),
('Wendy Mitchell', 'wendy.mitchell@example.com'),
('Xander Roberts', 'xander.roberts@example.com'),
('Yara Edwards', 'yara.edwards@example.com'),
('Zane Collins', 'zane.collins@example.com'),
('Amy Stewart', 'amy.stewart@example.com'),
('Brian Morris', 'brian.morris@example.com'),
('Cindy Rogers', 'cindy.rogers@example.com'),
('Derek Morgan', 'derek.morgan@example.com');

INSERT INTO product (name, quantity, price, observation, people_id) VALUES
('Laptop', 10, 999.99, 'High performance laptop', 1),
('Smartphone', 20, 499.99, 'Latest model smartphone', 2),
('Tablet', 15, 299.99, '10-inch screen tablet', 3),
('Smartwatch', 25, 199.99, 'Fitness tracking smartwatch', 4),
('Headphones', 50, 89.99, 'Noise-cancelling headphones', 5),
('Camera', 8, 599.99, 'DSLR camera with lens', 6),
('Printer', 12, 149.99, 'Wireless color printer', 7),
('Monitor', 18, 199.99, '27-inch 4K monitor', 8),
('Keyboard', 30, 49.99, 'Mechanical keyboard', 9),
('Mouse', 40, 29.99, 'Wireless mouse', 10),
('Speakers', 20, 79.99, 'Bluetooth speakers', 11),
('External Hard Drive', 25, 99.99, '1TB external hard drive', 12),
('Router', 10, 129.99, 'High-speed Wi-Fi router', 13),
('Webcam', 35, 39.99, 'HD webcam', 14),
('Microphone', 15, 59.99, 'USB condenser microphone', 15),
('Projector', 5, 499.99, '1080p home theater projector', 16),
('Gaming Console', 7, 399.99, 'Next-gen gaming console', 17),
('VR Headset', 10, 299.99, 'Virtual reality headset', 18),
('Smart Home Hub', 20, 99.99, 'Voice-controlled smart home hub', 19),
('Electric Scooter', 8, 499.99, 'Foldable electric scooter', 20),
('Drone', 12, 799.99, '4K camera drone', 21),
('3D Printer', 6, 299.99, 'Desktop 3D printer', 22),
('Fitness Tracker', 40, 49.99, 'Activity and sleep tracker', 23),
('Smart Thermostat', 15, 129.99, 'Wi-Fi smart thermostat', 24),
('Security Camera', 25, 79.99, 'Outdoor security camera', 25),
('Bluetooth Headset', 30, 49.99, 'Wireless Bluetooth headset', 26),
('Portable Charger', 50, 19.99, '10,000mAh portable charger', 27),
('Smart Light Bulb', 45, 14.99, 'Color-changing smart bulb', 28),
('Electric Toothbrush', 35, 69.99, 'Rechargeable electric toothbrush', 29),
('Robot Vacuum', 10, 299.99, 'Smart robot vacuum cleaner', 30);